// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        v6.30.0--rc1
// source: services/order-service/pkg/inventry/main.proto

package inventry

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Status struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Status) Reset() {
	*x = Status{}
	mi := &file_services_order_service_pkg_inventry_main_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Status) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Status) ProtoMessage() {}

func (x *Status) ProtoReflect() protoreflect.Message {
	mi := &file_services_order_service_pkg_inventry_main_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Status.ProtoReflect.Descriptor instead.
func (*Status) Descriptor() ([]byte, []int) {
	return file_services_order_service_pkg_inventry_main_proto_rawDescGZIP(), []int{0}
}

func (x *Status) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type GetAvailableStocksByIDIn struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAvailableStocksByIDIn) Reset() {
	*x = GetAvailableStocksByIDIn{}
	mi := &file_services_order_service_pkg_inventry_main_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAvailableStocksByIDIn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAvailableStocksByIDIn) ProtoMessage() {}

func (x *GetAvailableStocksByIDIn) ProtoReflect() protoreflect.Message {
	mi := &file_services_order_service_pkg_inventry_main_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAvailableStocksByIDIn.ProtoReflect.Descriptor instead.
func (*GetAvailableStocksByIDIn) Descriptor() ([]byte, []int) {
	return file_services_order_service_pkg_inventry_main_proto_rawDescGZIP(), []int{1}
}

func (x *GetAvailableStocksByIDIn) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetAvailableStocksByIDOut struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Item          *Item                  `protobuf:"bytes,1,opt,name=item,proto3" json:"item,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAvailableStocksByIDOut) Reset() {
	*x = GetAvailableStocksByIDOut{}
	mi := &file_services_order_service_pkg_inventry_main_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAvailableStocksByIDOut) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAvailableStocksByIDOut) ProtoMessage() {}

func (x *GetAvailableStocksByIDOut) ProtoReflect() protoreflect.Message {
	mi := &file_services_order_service_pkg_inventry_main_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAvailableStocksByIDOut.ProtoReflect.Descriptor instead.
func (*GetAvailableStocksByIDOut) Descriptor() ([]byte, []int) {
	return file_services_order_service_pkg_inventry_main_proto_rawDescGZIP(), []int{2}
}

func (x *GetAvailableStocksByIDOut) GetItem() *Item {
	if x != nil {
		return x.Item
	}
	return nil
}

type Item struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Count         int64                  `protobuf:"varint,3,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Item) Reset() {
	*x = Item{}
	mi := &file_services_order_service_pkg_inventry_main_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Item) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Item) ProtoMessage() {}

func (x *Item) ProtoReflect() protoreflect.Message {
	mi := &file_services_order_service_pkg_inventry_main_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Item.ProtoReflect.Descriptor instead.
func (*Item) Descriptor() ([]byte, []int) {
	return file_services_order_service_pkg_inventry_main_proto_rawDescGZIP(), []int{3}
}

func (x *Item) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Item) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Item) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

type BuyStocksByIDIn struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Count         int64                  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BuyStocksByIDIn) Reset() {
	*x = BuyStocksByIDIn{}
	mi := &file_services_order_service_pkg_inventry_main_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BuyStocksByIDIn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuyStocksByIDIn) ProtoMessage() {}

func (x *BuyStocksByIDIn) ProtoReflect() protoreflect.Message {
	mi := &file_services_order_service_pkg_inventry_main_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuyStocksByIDIn.ProtoReflect.Descriptor instead.
func (*BuyStocksByIDIn) Descriptor() ([]byte, []int) {
	return file_services_order_service_pkg_inventry_main_proto_rawDescGZIP(), []int{4}
}

func (x *BuyStocksByIDIn) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *BuyStocksByIDIn) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

type BuyStocksByIDOut struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BuyStocksByIDOut) Reset() {
	*x = BuyStocksByIDOut{}
	mi := &file_services_order_service_pkg_inventry_main_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BuyStocksByIDOut) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuyStocksByIDOut) ProtoMessage() {}

func (x *BuyStocksByIDOut) ProtoReflect() protoreflect.Message {
	mi := &file_services_order_service_pkg_inventry_main_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuyStocksByIDOut.ProtoReflect.Descriptor instead.
func (*BuyStocksByIDOut) Descriptor() ([]byte, []int) {
	return file_services_order_service_pkg_inventry_main_proto_rawDescGZIP(), []int{5}
}

func (x *BuyStocksByIDOut) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_services_order_service_pkg_inventry_main_proto protoreflect.FileDescriptor

var file_services_order_service_pkg_inventry_main_proto_rawDesc = string([]byte{
	0x0a, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2f, 0x6f, 0x72, 0x64, 0x65, 0x72,
	0x2d, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x69, 0x6e, 0x76,
	0x65, 0x6e, 0x74, 0x72, 0x79, 0x2f, 0x6d, 0x61, 0x69, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x08, 0x69, 0x6e, 0x76, 0x65, 0x6e, 0x74, 0x72, 0x79, 0x22, 0x20, 0x0a, 0x06, 0x53, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x2a, 0x0a, 0x18,
	0x47, 0x65, 0x74, 0x41, 0x76, 0x61, 0x69, 0x6c, 0x61, 0x62, 0x6c, 0x65, 0x53, 0x74, 0x6f, 0x63,
	0x6b, 0x73, 0x42, 0x79, 0x49, 0x44, 0x49, 0x6e, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x3f, 0x0a, 0x19, 0x47, 0x65, 0x74, 0x41,
	0x76, 0x61, 0x69, 0x6c, 0x61, 0x62, 0x6c, 0x65, 0x53, 0x74, 0x6f, 0x63, 0x6b, 0x73, 0x42, 0x79,
	0x49, 0x44, 0x4f, 0x75, 0x74, 0x12, 0x22, 0x0a, 0x04, 0x69, 0x74, 0x65, 0x6d, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x69, 0x6e, 0x76, 0x65, 0x6e, 0x74, 0x72, 0x79, 0x2e, 0x49,
	0x74, 0x65, 0x6d, 0x52, 0x04, 0x69, 0x74, 0x65, 0x6d, 0x22, 0x40, 0x0a, 0x04, 0x49, 0x74, 0x65,
	0x6d, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69,
	0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0x37, 0x0a, 0x0f, 0x42,
	0x75, 0x79, 0x53, 0x74, 0x6f, 0x63, 0x6b, 0x73, 0x42, 0x79, 0x49, 0x44, 0x49, 0x6e, 0x12, 0x0e,
	0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x14,
	0x0a, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x63,
	0x6f, 0x75, 0x6e, 0x74, 0x22, 0x2a, 0x0a, 0x10, 0x42, 0x75, 0x79, 0x53, 0x74, 0x6f, 0x63, 0x6b,
	0x73, 0x42, 0x79, 0x49, 0x44, 0x4f, 0x75, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x32, 0xf2, 0x01, 0x0a, 0x08, 0x69, 0x6e, 0x76, 0x65, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x63, 0x0a,
	0x16, 0x47, 0x65, 0x74, 0x41, 0x76, 0x61, 0x69, 0x6c, 0x61, 0x62, 0x6c, 0x65, 0x53, 0x74, 0x6f,
	0x63, 0x6b, 0x73, 0x42, 0x79, 0x49, 0x44, 0x12, 0x22, 0x2e, 0x69, 0x6e, 0x76, 0x65, 0x6e, 0x74,
	0x72, 0x79, 0x2e, 0x47, 0x65, 0x74, 0x41, 0x76, 0x61, 0x69, 0x6c, 0x61, 0x62, 0x6c, 0x65, 0x53,
	0x74, 0x6f, 0x63, 0x6b, 0x73, 0x42, 0x79, 0x49, 0x44, 0x49, 0x6e, 0x1a, 0x23, 0x2e, 0x69, 0x6e,
	0x76, 0x65, 0x6e, 0x74, 0x72, 0x79, 0x2e, 0x47, 0x65, 0x74, 0x41, 0x76, 0x61, 0x69, 0x6c, 0x61,
	0x62, 0x6c, 0x65, 0x53, 0x74, 0x6f, 0x63, 0x6b, 0x73, 0x42, 0x79, 0x49, 0x44, 0x4f, 0x75, 0x74,
	0x22, 0x00, 0x12, 0x48, 0x0a, 0x0d, 0x42, 0x75, 0x79, 0x53, 0x74, 0x6f, 0x63, 0x6b, 0x73, 0x42,
	0x79, 0x49, 0x44, 0x12, 0x19, 0x2e, 0x69, 0x6e, 0x76, 0x65, 0x6e, 0x74, 0x72, 0x79, 0x2e, 0x42,
	0x75, 0x79, 0x53, 0x74, 0x6f, 0x63, 0x6b, 0x73, 0x42, 0x79, 0x49, 0x44, 0x49, 0x6e, 0x1a, 0x1a,
	0x2e, 0x69, 0x6e, 0x76, 0x65, 0x6e, 0x74, 0x72, 0x79, 0x2e, 0x42, 0x75, 0x79, 0x53, 0x74, 0x6f,
	0x63, 0x6b, 0x73, 0x42, 0x79, 0x49, 0x44, 0x4f, 0x75, 0x74, 0x22, 0x00, 0x12, 0x37, 0x0a, 0x0b,
	0x48, 0x65, 0x61, 0x6c, 0x74, 0x68, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x12, 0x10, 0x2e, 0x69, 0x6e,
	0x76, 0x65, 0x6e, 0x74, 0x72, 0x79, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x1a, 0x10, 0x2e,
	0x69, 0x6e, 0x76, 0x65, 0x6e, 0x74, 0x72, 0x79, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22,
	0x00, 0x28, 0x01, 0x30, 0x01, 0x42, 0x0c, 0x5a, 0x0a, 0x2e, 0x2f, 0x69, 0x6e, 0x76, 0x65, 0x6e,
	0x74, 0x72, 0x79, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
})

var (
	file_services_order_service_pkg_inventry_main_proto_rawDescOnce sync.Once
	file_services_order_service_pkg_inventry_main_proto_rawDescData []byte
)

func file_services_order_service_pkg_inventry_main_proto_rawDescGZIP() []byte {
	file_services_order_service_pkg_inventry_main_proto_rawDescOnce.Do(func() {
		file_services_order_service_pkg_inventry_main_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_services_order_service_pkg_inventry_main_proto_rawDesc), len(file_services_order_service_pkg_inventry_main_proto_rawDesc)))
	})
	return file_services_order_service_pkg_inventry_main_proto_rawDescData
}

var file_services_order_service_pkg_inventry_main_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_services_order_service_pkg_inventry_main_proto_goTypes = []any{
	(*Status)(nil),                    // 0: inventry.Status
	(*GetAvailableStocksByIDIn)(nil),  // 1: inventry.GetAvailableStocksByIDIn
	(*GetAvailableStocksByIDOut)(nil), // 2: inventry.GetAvailableStocksByIDOut
	(*Item)(nil),                      // 3: inventry.Item
	(*BuyStocksByIDIn)(nil),           // 4: inventry.BuyStocksByIDIn
	(*BuyStocksByIDOut)(nil),          // 5: inventry.BuyStocksByIDOut
}
var file_services_order_service_pkg_inventry_main_proto_depIdxs = []int32{
	3, // 0: inventry.GetAvailableStocksByIDOut.item:type_name -> inventry.Item
	1, // 1: inventry.inventry.GetAvailableStocksByID:input_type -> inventry.GetAvailableStocksByIDIn
	4, // 2: inventry.inventry.BuyStocksByID:input_type -> inventry.BuyStocksByIDIn
	0, // 3: inventry.inventry.HealthCheck:input_type -> inventry.Status
	2, // 4: inventry.inventry.GetAvailableStocksByID:output_type -> inventry.GetAvailableStocksByIDOut
	5, // 5: inventry.inventry.BuyStocksByID:output_type -> inventry.BuyStocksByIDOut
	0, // 6: inventry.inventry.HealthCheck:output_type -> inventry.Status
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_services_order_service_pkg_inventry_main_proto_init() }
func file_services_order_service_pkg_inventry_main_proto_init() {
	if File_services_order_service_pkg_inventry_main_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_services_order_service_pkg_inventry_main_proto_rawDesc), len(file_services_order_service_pkg_inventry_main_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_services_order_service_pkg_inventry_main_proto_goTypes,
		DependencyIndexes: file_services_order_service_pkg_inventry_main_proto_depIdxs,
		MessageInfos:      file_services_order_service_pkg_inventry_main_proto_msgTypes,
	}.Build()
	File_services_order_service_pkg_inventry_main_proto = out.File
	file_services_order_service_pkg_inventry_main_proto_goTypes = nil
	file_services_order_service_pkg_inventry_main_proto_depIdxs = nil
}
