// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        v6.30.0--rc1
// source: services/order-service/pkg/api/main.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Status struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Status) Reset() {
	*x = Status{}
	mi := &file_services_order_service_pkg_api_main_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Status) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Status) ProtoMessage() {}

func (x *Status) ProtoReflect() protoreflect.Message {
	mi := &file_services_order_service_pkg_api_main_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Status.ProtoReflect.Descriptor instead.
func (*Status) Descriptor() ([]byte, []int) {
	return file_services_order_service_pkg_api_main_proto_rawDescGZIP(), []int{0}
}

func (x *Status) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type GetOrderByIDIn struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrderByIDIn) Reset() {
	*x = GetOrderByIDIn{}
	mi := &file_services_order_service_pkg_api_main_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrderByIDIn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderByIDIn) ProtoMessage() {}

func (x *GetOrderByIDIn) ProtoReflect() protoreflect.Message {
	mi := &file_services_order_service_pkg_api_main_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderByIDIn.ProtoReflect.Descriptor instead.
func (*GetOrderByIDIn) Descriptor() ([]byte, []int) {
	return file_services_order_service_pkg_api_main_proto_rawDescGZIP(), []int{1}
}

func (x *GetOrderByIDIn) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type GetOrderByIDOut struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrderByIDOut) Reset() {
	*x = GetOrderByIDOut{}
	mi := &file_services_order_service_pkg_api_main_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrderByIDOut) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderByIDOut) ProtoMessage() {}

func (x *GetOrderByIDOut) ProtoReflect() protoreflect.Message {
	mi := &file_services_order_service_pkg_api_main_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderByIDOut.ProtoReflect.Descriptor instead.
func (*GetOrderByIDOut) Descriptor() ([]byte, []int) {
	return file_services_order_service_pkg_api_main_proto_rawDescGZIP(), []int{2}
}

func (x *GetOrderByIDOut) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type UpdateOrderByIDIn struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateOrderByIDIn) Reset() {
	*x = UpdateOrderByIDIn{}
	mi := &file_services_order_service_pkg_api_main_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateOrderByIDIn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateOrderByIDIn) ProtoMessage() {}

func (x *UpdateOrderByIDIn) ProtoReflect() protoreflect.Message {
	mi := &file_services_order_service_pkg_api_main_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateOrderByIDIn.ProtoReflect.Descriptor instead.
func (*UpdateOrderByIDIn) Descriptor() ([]byte, []int) {
	return file_services_order_service_pkg_api_main_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateOrderByIDIn) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type UpdateOrderByIDOut struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateOrderByIDOut) Reset() {
	*x = UpdateOrderByIDOut{}
	mi := &file_services_order_service_pkg_api_main_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateOrderByIDOut) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateOrderByIDOut) ProtoMessage() {}

func (x *UpdateOrderByIDOut) ProtoReflect() protoreflect.Message {
	mi := &file_services_order_service_pkg_api_main_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateOrderByIDOut.ProtoReflect.Descriptor instead.
func (*UpdateOrderByIDOut) Descriptor() ([]byte, []int) {
	return file_services_order_service_pkg_api_main_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateOrderByIDOut) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_services_order_service_pkg_api_main_proto protoreflect.FileDescriptor

var file_services_order_service_pkg_api_main_proto_rawDesc = string([]byte{
	0x0a, 0x29, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2f, 0x6f, 0x72, 0x64, 0x65, 0x72,
	0x2d, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x61, 0x70, 0x69,
	0x2f, 0x6d, 0x61, 0x69, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x6f, 0x72, 0x64,
	0x65, 0x72, 0x22, 0x20, 0x0a, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x16, 0x0a, 0x06,
	0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x22, 0x28, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x4f, 0x72, 0x64, 0x65, 0x72,
	0x42, 0x79, 0x49, 0x44, 0x49, 0x6e, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x29,
	0x0a, 0x0f, 0x47, 0x65, 0x74, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x42, 0x79, 0x49, 0x44, 0x4f, 0x75,
	0x74, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x2b, 0x0a, 0x11, 0x55, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x42, 0x79, 0x49, 0x44, 0x49, 0x6e, 0x12, 0x16,
	0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x2c, 0x0a, 0x12, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x4f, 0x72, 0x64, 0x65, 0x72, 0x42, 0x79, 0x49, 0x44, 0x4f, 0x75, 0x74, 0x12, 0x16, 0x0a, 0x06,
	0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x32, 0xc5, 0x01, 0x0a, 0x05, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x12, 0x3f,
	0x0a, 0x0c, 0x47, 0x65, 0x74, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x42, 0x79, 0x49, 0x44, 0x12, 0x15,
	0x2e, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x2e, 0x47, 0x65, 0x74, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x42,
	0x79, 0x49, 0x44, 0x49, 0x6e, 0x1a, 0x16, 0x2e, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x2e, 0x47, 0x65,
	0x74, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x42, 0x79, 0x49, 0x44, 0x4f, 0x75, 0x74, 0x22, 0x00, 0x12,
	0x48, 0x0a, 0x0f, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x42, 0x79,
	0x49, 0x44, 0x12, 0x18, 0x2e, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x42, 0x79, 0x49, 0x44, 0x49, 0x6e, 0x1a, 0x19, 0x2e, 0x6f,
	0x72, 0x64, 0x65, 0x72, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4f, 0x72, 0x64, 0x65, 0x72,
	0x42, 0x79, 0x49, 0x44, 0x4f, 0x75, 0x74, 0x22, 0x00, 0x12, 0x31, 0x0a, 0x0b, 0x48, 0x65, 0x61,
	0x6c, 0x74, 0x68, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x12, 0x0d, 0x2e, 0x6f, 0x72, 0x64, 0x65, 0x72,
	0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x1a, 0x0d, 0x2e, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x2e,
	0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x00, 0x28, 0x01, 0x30, 0x01, 0x42, 0x07, 0x5a, 0x05,
	0x2e, 0x2f, 0x61, 0x70, 0x69, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
})

var (
	file_services_order_service_pkg_api_main_proto_rawDescOnce sync.Once
	file_services_order_service_pkg_api_main_proto_rawDescData []byte
)

func file_services_order_service_pkg_api_main_proto_rawDescGZIP() []byte {
	file_services_order_service_pkg_api_main_proto_rawDescOnce.Do(func() {
		file_services_order_service_pkg_api_main_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_services_order_service_pkg_api_main_proto_rawDesc), len(file_services_order_service_pkg_api_main_proto_rawDesc)))
	})
	return file_services_order_service_pkg_api_main_proto_rawDescData
}

var file_services_order_service_pkg_api_main_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_services_order_service_pkg_api_main_proto_goTypes = []any{
	(*Status)(nil),             // 0: order.Status
	(*GetOrderByIDIn)(nil),     // 1: order.GetOrderByIDIn
	(*GetOrderByIDOut)(nil),    // 2: order.GetOrderByIDOut
	(*UpdateOrderByIDIn)(nil),  // 3: order.UpdateOrderByIDIn
	(*UpdateOrderByIDOut)(nil), // 4: order.UpdateOrderByIDOut
}
var file_services_order_service_pkg_api_main_proto_depIdxs = []int32{
	1, // 0: order.order.GetOrderByID:input_type -> order.GetOrderByIDIn
	3, // 1: order.order.UpdateOrderByID:input_type -> order.UpdateOrderByIDIn
	0, // 2: order.order.HealthCheck:input_type -> order.Status
	2, // 3: order.order.GetOrderByID:output_type -> order.GetOrderByIDOut
	4, // 4: order.order.UpdateOrderByID:output_type -> order.UpdateOrderByIDOut
	0, // 5: order.order.HealthCheck:output_type -> order.Status
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_services_order_service_pkg_api_main_proto_init() }
func file_services_order_service_pkg_api_main_proto_init() {
	if File_services_order_service_pkg_api_main_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_services_order_service_pkg_api_main_proto_rawDesc), len(file_services_order_service_pkg_api_main_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_services_order_service_pkg_api_main_proto_goTypes,
		DependencyIndexes: file_services_order_service_pkg_api_main_proto_depIdxs,
		MessageInfos:      file_services_order_service_pkg_api_main_proto_msgTypes,
	}.Build()
	File_services_order_service_pkg_api_main_proto = out.File
	file_services_order_service_pkg_api_main_proto_goTypes = nil
	file_services_order_service_pkg_api_main_proto_depIdxs = nil
}
