server:
  host: 0.0.0.0
  port: 7610
  timeout: 300s 

rpc:
  host: 0.0.0.0
  port: 7600
  maxProcessingTime: 1000000ms
  tls: false

logger:
  logLevel: error

inventry:
  host: 0.0.0.0
  port: 7500
  isSecure: false